[build-system]
requires = ["maturin", "cffi"]
build-backend = "maturin"

[tool.maturin]
bindings = "cffi"
manylinux = "off"

[package.metadata.maturin]
requires-python = ">=3.5"
classifier = ["Programming Language :: Python"]
