name: manylinux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: konstin2/maturin:master

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: py-deps
        run: |
          pip install --upgrade pip
          pip install cffi maturin .
      - name: py-install
        run: |
          maturin build --release      
      - uses: actions/upload-artifact@v1
        name: upload-wheel
        with:
          name: wheel-manylinux
          path: target/wheels/

        
