name: manylinux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: konstin2/maturin:master
      volumes: 
        - .:/io

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: maturin-build
        run: |
          hostname
          uname -a
          cargo --version
          maturin --version
          maturin build --release      
      - uses: actions/upload-artifact@v1
        name: upload-wheel
        with:
          name: wheel-manylinux
          path: target/wheels/

        
